---
title: "Ch. 2: How to Search?"
subtitle: 'Learning and implementing search strategies'
author: Maia L. Southwick
date: "2024-12-19"
format: html
toc: true
number-sections: true

---
# The Job Search Mindset

Finding a full-time job is a process. It can be overwhelming yet exciting to see all of the possibilities for the next chapter of your life.

There's an aspect of vulnerability in the job search. You're summarizing all of the experiences and skills you believe are relevant to a position into a single application, submitting it, and waiting to be judged in a way that will could significantly changed your life.

Rejections are going to happen, or even worse, you won't receive any response from an employer on the status of your application. As you go on this journey, a little advice:

**Be...**

- ***Open-minded***: There could job titles or positions you may not be aware of that match your interests and/or skillset. You can focus your job search on a certain role, but read through job descriptions to make sure they're aligning with your own career priorities. Try to expand your search to include titles that are adjacent to your interests. You can search or ask ChatGPT about suggested job titles based on your goals or current skill set.
- ***Cautious***: In the face of mounting rejections or if the job search drags on, a reasonable reaction is to lower your standards for the type of position you're willing to take on. While managing your expectations for an entry-level role is appropriate, accepting a position at a company that exploits desperate or naive job seekers may set you on an untowardly career path. 
    - Because there's always going to be rent due at the end of the month, it's okay to take on a temporary or part-time job. 
    - If there are restrictions on the types of positions you can work post-grad (i.e., international students), UCD students and alumni have access to [GoinGlobal](https://siss.ucdavis.edu/goinglobal). They advertise resources for H1B visa holders.
- ***Patient (with yourself)***: Find ways to demonstrate kindness to yourself during this process. Stay connected with those who matter to you, build in moments of care or play into your everyday routine, and treat the job search as a part-time job. Dedicate time to the search, but once the job is done for the day, fill your time in other ways.

# LinkedIn: Navigating the "Jobs" Section

## Search Functionality

photo of sample job search on linkedin

highlight important components

## Search Terms

Below is a sample set of keywords for different job types, generated from ChatGPT (OpenAI, 2024). 

Here is what I asked ChatGPT, *"What are some related keywords to a behavior technician position?"*. It generated keywords related to the role I was interested in (Behavior Technician), skills, work environment, and more. For our purposes, we will use the 'General Role Keywords' to plug into our LinkedIn search. 

However, the other keyword output could also be helpful when you're trying to craft a resume as long as you're accurately and honestly representing your skills and experiences. Sometimes recruiters and hiring managers use automated programs to filter resumes (for better or for worse ~~cough cough~~), and so having relevant keywords in your resume could be helpful.


| Job Type    | Keywords                                               |
| ----------- | ------------------------------------------------------ |
| Behavior Technician   |  applied behavioral analysis, registered behavior technician, behavioral therapy, intervnetion specialist, autism spectrum disorder |
| Others

A list of relevant, entry-level job titles can be found [here (for Psychology)](https://careercenter.ucdavis.edu/career-discovery/undergraduate-students/what-can-i-do/majors-data?mcid=191) and [here (for Cognitive Science)](https://careercenter.ucdavis.edu/career-discovery/undergraduate-students/what-can-i-do/majors-data?mcid=269). You can loop some of the titles listed into your search strategy.

:::{.callout-caution}
The term 'research' in job search land is pretty broad. Across all fields and industries, there is research being done. This means when typing in 
:::
<!--- engagement opportunity, have them ask ChatGPT a question, we'll use a live example for the run-through --->

### Filtering

### Setting Up Search Alerts

1. Main way

2. As mentioned earlier, if there's an organization that you're interested in, you can "Follow" an organization. 
    a. You can either follow the people associated with the organization who may be likely to re-post job ads. You can find these by going to the 'People' tab. *OR, to avoid spamming your homepage with strangers' posts...*
    b. You can go to the 'Jobs' page, click on 'Create job alert', and put in the type of roles you're interested in and what locations you'd be open to working at. 
    c. Be sure to review the types of positions that individuals under the 'People' tab may have that you're interested in and determine where common work locations are (either what's listed as the head quarters location under company's name or in the 'About' tab).
    
<!--- Insert image here with all the above components highlighted. --->


<!---This will be an active engagement portion; have them sign-up for an organization they may be interested in. Be sure to give some examples. I can 'create a job alert' as a walkthrough.--->

### Setting Up a Folder in Gmail/Microsoft Inbox

### Pro-tips

- **Being quick to apply is in your favor** if a submission deadline is not specified. However, ensure you're submitting quality materials for the application. We will not be covering crafting a resume in full for this workshop.


# References

OpenAI. (2024). ChatGPT (December 19 version). OpenAI. https://openai.com
