---
title: "pug-job-search"
author: "Maia L. Southwick"
format: revealjs
---

# Welcome!

- Access the workshop materials here: [https://msouthwick-edu.github.io/2025wq_psych-job-search/](https://msouthwick-edu.github.io/2025wq_psych-job-search/)
- Complete a pre-workshop survey here: [https://tinyurl.com/2umhdys3](https://tinyurl.com/2umhdys3)
- You will need easy access to your laptop and connection to internet.

# Overview

## Agenda

1. Where to search?
2. How to search?
3. What comes up in the search?

<!-- -->

## Goals

1. Where to search?

  - **Identify relevant places to source jobs**
2. How to search?

  - **Leverage tools to aid your job search**
3. What comes up in the search?

  - **Understand the main components of a job posting to inform your search**
 

# Introductions

## Who I am

- Maia Southwick (she/her)
- PhD student studying developmental and quantitative psychology
- B.S. in Psychology and Health, Society, & Policy
- Worked in a variety of professional contexts

<!-- Mention transitioning out of undergrad had its own challenges --->

## Who you are

- Turn to your neighbor(s) and introduce yourself
  - Your name, major, year in school
  - Why did you choose your major?
  - What are your career goals?
  
<!-- Now that we've introduced ourselves, let's learn more about some strategies on how to take this mext step of your career journey together -->

# Where to Search

- 

- Take time to set up accounts and troubleshoot
? Take time to exchange with neighbors and the group of other organizations or places that they've found jobs positions at

<!-- Sometimes one of the hardest things of any new process, -->

# How to Search

- Brainstorm with neighbors and Maia of positions they're interested in
- Take time to generate search terms via ChatGPT
- Take time to set up a search alert

# What Comes Up

- Select some of those search results and review.
- Compare with neighbors the positions you've found.
  - How do the benefits differ?
  - How do the descriptions differ?
  
# Next Steps

- Schedule a time or start date for your job search. Stick to it. Treat it like a part-time position.
- Find someone who can do sniff tests for you. It can be the neighbor you chatted with today, a close friend or family member, or an advisor. Ultimately, the positions you apply for and the jobs you take is your choice, but it'll be good to have someone who can help you look out for red flags.